# -*- coding: utf-8 -*-
"""scrape_from_email.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17TfB9rGQqkhx8x8j2z-Dx2oYNCd_BzaZ
"""

import numpy as np
import pandas as pd
import email, getpass, imaplib, os, re
import matplotlib.pyplot as plt
import datetime 
from datetime import date, timedelta
from bs4 import BeautifulSoup

# connect to gmail imap server
m = imaplib.IMAP4_SSL('imap.gmail.com')
# fill in username
username = '#####'
# fill in password
password = '#####'
# login
m.login(username, password)

status,messages = m.select('re_dashboard')

if status != 'OK':
  print ('Inocrrect mailbox')
  
  exit()

print (messages)

# getting the ids for the emails that were received today. 
# needs to be in this format 
#yesterday = (date.today() - timedelta(1)).strftime('%d-%b-%Y')
df_date = date.today().strftime('%m/%d/%Y')
date = date.today().strftime('%d-%b-%Y')
resp, items = m.search(None, '(SENTON {date})'.format(date=date))
items = items[0].split()
#items = b','.join(items[0].split())
items

# looping over the emails we searched for above
props =[] 
for emailid in items:
  #temp_dict={}
  # fetching the items based on 
  resp, data = m.uid('fetch', emailid, '(RFC822)')
  email_body = data[0][1]
  mail = email.message_from_bytes(email_body)
  if mail.is_multipart():
    for part in mail.walk():
      body = part.get_payload(decode=True)
      soup = BeautifulSoup(str(body), 'html.parser')
      # this is finding all the tables with that certain style(each property has exactly 1 of these tables)
      breakdown = soup.find_all('table',{'style':'border-collapse:collapse;margin-bottom:2px'})
      #creating a list that contains a bs4.element for each property with all the information
      for i in breakdown:
        props.append(i)

alls = []
price =[]
for item in props:
  price.append(item.table('span', text=True))
for i in range(len(price)):
  alls.append([tag.text for tag in price[i]])

#date = date.today().strftime('%d-%b-%Y')
prop_dict={}
prop_dict['data']=[]
for i in range(len(alls)):
  prop_dict['data'].append({
      'address': alls[i][0],
      'display_price': alls[i][1], 
      'listing_id': alls[i][3],
      'status': alls[i][5],
      'sqft' : alls[i][7],
      'bed': alls[i][9],
      'bath': alls[i][10],
      'pool': alls[i][12],
      'view': alls[i][14],
      'yrbuilt': alls[i][16],
      'type': alls[i][18],
      'contract_status_change_date': df_date
  })

props = pd.DataFrame(prop_dict['data'],columns=['address', 'display_price', 'listing_id', 'status', 'sqft', 'bed', 'bath', 'pool', 'view', 'yrbuilt', 'type', 'contract_status_change_date'])
props